#!/usr/bin/env sh

NODE_ID=$1

curl -sX POST --data '{
    "jsonrpc":"2.0",
    "id"     :1,
    "method" :"info.peers",
    "params": {
        "nodeIDs": []
    }
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/info | jq '.result.peers' | recs fromjsonarray | recs grep "{{nodeID}} eq \"$NODE_ID\"" | jq
